base_url = "https://konceptosociala.eu.org/socio"
compile_sass = true
output_dir = "docs"
build_search_index = true

[markdown]
highlight_code = true

[extra]
socio_title = "Socio Theme Demo"
socio_favicon = "img/socio_favicon.svg"
socio_logo = "img/socio.svg"

socio_navbar_links = [
    { title = "Home", link = "/" },
    { title = "Blog", link = "/blog" },
    { title = "Disabled" },
    { title = "About", dropdown = [
        ["Info", "/info"],
        ["Socio on GitHub", "https://github.com/konceptosociala/socio"]
    ] }
]

socio_banner_display = true
socio_banner_logo = "img/socio_favicon_variant.svg"
socio_banner_logo_width = 144
socio_banner_heading = "Socio Zola Theme"
socio_banner_descr = "Simple. Libre. Humane"