base_url = "https://konceptosociala.eu.org/socio"
compile_sass = true
output_dir = "docs"
default_language = "en"
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
# General
socio_title = "Socio Theme Demo"
socio_favicon = "/img/socio_favicon.svg"
socio_logo = "/img/socio.svg"

# Navbar links
socio_navbar_links = [
    { key = "home", link = "/" },
    { key = "blog", link = "/blog/" },
    { key = "disabled" },
    { key = "about", dropdown = [
        ["info", "/info/"],
        ["socio_on_github", "https://github.com/konceptosociala/socio"]
    ] }
]

# Multilingualism (uncomment to enable language switcher)
socio_languages = [
    { code = "default", name = "English", flag = "us" },
    { code = "ua", name = "Українська", flag = "ua" },
    { code = "sr", name = "Srpski", flag = "rs" },
]

# Homepage banner
socio_banner_display = true
socio_banner_logo = "/img/socio_favicon_variant.svg"
socio_banner_logo_width = 144

# Social (comment to hide)
socio_github = "https://github.com/konceptosociala/socio"
socio_mail = "#"
socio_telegram = "#"
socio_discord = "#"
socio_facebook = "#"
socio_insta = "#"
socio_linkedin = "#"
socio_reddit = "#"
socio_twitter = "#"
socio_youtube = "#"

# Colors
socio_text_color = "#F5F5F5"
socio_link_color = "#F5F5F5"
socio_code_color = "#F5F5F5"
socio_code_bg = "#2b303b"

socio_post_bg = "#423e3b"
socio_header_bg = "#08090A"
socio_footer_bg = "#423e3b"
socio_404_bg = "#F34E00"
socio_page_bg = "#F34E00"
socio_banner_bg = "#423E3B"

socio_pill_bg = "dark"
socio_project_bg = "dark"
socio_pill_btn = "primary"
socio_banner_btn = "success"   # Bootstrap value (primary, info etc.)
socio_search_btn = "light"     # or custom for `btn-*` class
socio_back_btn = "dark"        # Example: .btn-myownclass

# Misc
socio_forkme = { enabled = true, repo = "https://github.com/konceptosociala/socio", label = "Fork me on GitHub"}

[translations]
search = "Search"
read_more = "Read more"
banner_button = "Learn more"
banner_heading = "Socio Zola Theme"
banner_descr = "Simple. Libre. Humane"

home = "Home"
blog = "Blog"
disabled = "Disabled"
about = "About"
info = "Info"
socio_on_github = "Socio on GitHub"

[languages.ua]

[languages.ua.translations]
search = "Пошук"
read_more = "Читати далі"
banner_button = "Дізнатися більше"
banner_heading = "Socio тема для Zola"
banner_descr = "Проста. Вільна. Людяна"

home = "Головна"
blog = "Блог"
disabled = "Відключено"
about = "Про нас"
info = "Інформація"
socio_on_github = "Socio на GitHub"

[languages.sr]

[languages.sr.translations]
search = "Pretraga"
read_more = "Opširnije"
banner_button = "Saznajte više"
banner_heading = "Socio tema za Zola"
banner_descr = "Jednostavna. Slobodna. Čovečana"

home = "Početna"
blog = "Blog"
disabled = "Onemogućeno"
about = "O nama"
info = "Informacije"
socio_on_github = "Socio na GitHub"