base_url = "https://konceptosociala.eu.org/socio"
compile_sass = true
output_dir = "docs"
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
# General
socio_title = "Socio Theme Demo"
socio_favicon = "/img/socio_favicon.svg"
socio_logo = "/img/socio.svg"

# Navbar links
socio_navbar_links = [
    { title = "Home", link = "/" },
    { title = "Blog", link = "/blog/" },
    { title = "Disabled" },
    { title = "About", dropdown = [
        ["Info", "/info/"],
        ["Socio on GitHub", "https://github.com/konceptosociala/socio"]
    ] }
]

# Homepage banner
socio_banner_display = true
socio_banner_logo = "/img/socio_favicon_variant.svg"
socio_banner_logo_width = 144
socio_banner_heading = "Socio Zola Theme"
socio_banner_descr = "Simple. Libre. Humane"

# Social (comment to hide)
socio_github = "https://github.com/konceptosociala/socio"
socio_mail = "#"
socio_telegram = "#"
socio_discord = "#"
socio_facebook = "#"
socio_insta = "#"
socio_linkedin = "#"
socio_reddit = "#"
socio_twitter = "#"
socio_youtube = "#"

# Colors
socio_text_color = "#F5F5F5"
socio_link_color = "#F5F5F5"
socio_code_color = "#F5F5F5"
socio_code_bg = "#2b303b"

socio_header_bg = "#08090A"
socio_footer_bg = "#423e3b"
socio_404_bg = "#F34E00"
socio_page_bg = "#F34E00"
socio_banner_bg = "#423E3B"

socio_banner_btn = "success"   # Bootstrap value (primary, info etc.)
socio_search_btn = "light"     # or custom for `btn-*` class

# Misc
socio_forkme = { enabled = true, repo = "https://github.com/konceptosociala/socio", label = "Fork me on GitHub"}